public_key: "BKY8lI5pWtgXAy58wmhUzAa8nxqsjVFNJHgx2eLEqNugE_A9odz1OAOy0yv9gJZq0c_KM9c7vFH_6hcddZXOyxA"
private_key: "ho80uFaPMHoVhCj8YuDWMWnR_wHrJFGyOVRKRVWeBN8"
subscriber: "mailto:example@example.com"
